### ISSUE TITLE
Mostrar las fechas de cumpleaños

### ISSUE THREAD

**Issue by Panchoclo01** [JajoScript/waton#5]
Me gustaría ver un comando en el waton bot, que, al utilizarlo, te muestre todos los cumpleaños registrados, ordenados por los días restantes de menor a mayor. Así, puedo saber los cumpleaños de mis compañeros y cual es el cumpleaños mas cercano.

Saludos #2

**Comment by JajoScript** [comment]
Excelente propuesta, el equipo de desarrollo ya esta trabajando en esto.

**Comment by JajoScript** [comment]
Estimado, 

Su comando, fue implementando en el bot. Utilizar el comando **cumpleaños** para obtener los resultados esperados.

Saludos,
